[build]
  publish = "."

[[redirects]]
  from = "/api/fred/*"
  to = "https://api.stlouisfed.org/fred/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/bis/*"
  to = "https://stats.bis.org/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
